FROM openjdk:11-jdk
LABEL authors="loky1"
CMD ["java", "-jar", "/build/libs/docker-example-0.0.1-SANPSHOT.jar"]
#WORKDIR /app
#ARG JAR_FILE=build/libs/docker-0.0.1-SNAPSHOT.jar
#ADD ${JAR_FILE} docker-springboot.jar

#EXPOSE 8081

#ENTRYPOINT ["java", "-Djava.securiy"]
